version: '3.5'
services:
  udemy-lumen-author:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: udemy-lumen-author
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
